name: Publier

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Installation des packages système
        run: sudo apt install language-pack-fr -y
      - name: Checkout du dépôt
        uses: actions/checkout@v4
      - name: Installation de Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Mise à jour de pip
        run: python -m pip install --upgrade pip
      - name: Installation des dépendances
        run: pip install -r requirements.txt
      - name: Installation de la clef SSH
        run: |
          mkdir $HOME/.ssh
          echo "${{ secrets.SSH_KEY }}" >> $HOME/.ssh/id_rsa
          chmod 400 $HOME/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ vars.SSH_HOST }} >> $HOME/.ssh/known_hosts
      - name: Génération et déploiement du site
        env:
          SSH_HOST: ${{ vars.SSH_HOST }}
          SSH_PATH: ${{ vars.SSH_PATH }}
          SSH_USER: ${{ vars.SSH_USER }}
          BASE_URL: ${{ vars.BASE_URL }}
          APPEND_HTML_TO_URLS: ${{ vars.APPEND_HTML_TO_URLS }}
          MINIFY_HTML: ${{ vars.MINIFY_HTML }}
        run: invoke clean build publish